Pagination - add custom styling
EQWorks/lumen-labs pull request #180
Opened 2023-04-17 16:35 UTC by amy83762100

2023-04-17 20:17 UTC, geoerika requested changes
See my comment.

2023-04-17 20:17 UTC, geoerika commented on src/components/pagination.js
> +      ${classes.container || ''}`,
@amy83762100 need to move all these classes before any other styling, after the class names, for all classes keys.

2023-04-18 13:51 UTC, Hamaad102 approved these changes

2023-04-18 13:59 UTC, geoerika approved these changes

2023-04-18 14:22 UTC, merged