switch - change color classname & custom classes logic
EQWorks/lumen-labs pull request #24
Opened 2021-07-19 19:16 UTC by kc-leung

- changed color classname to the new added color palette
- changed switch base component custom classes logic

2021-07-20 16:34 UTC, hyx131 commented on src/base-components/range-slider-base/index.js
> +    sliderTrack: `${classes.sliderTrack ? `bg-${classes.sliderTrack}-200` : 'bg-secondary-400'}`,
same comment as https://github.com/EQWorks/lumen-labs/pull/21#discussion_r673276823

2021-07-23 20:29 UTC, woozyking approved these changes
For switches, shall we also consider accessibility measures such as including stripes for colour-weak/blind users?

2021-07-26 19:53 UTC, YizhiCatherineZhang requested changes
Since this is built with Tailwind CSS and the color guide is there. I suggest you change the color based on our color guide line to keep the consistency. 

Function wise are good, and we can change the style later.

2021-07-27 18:38 UTC, woozyking commented
this might just be me but the rectangle inner span seems to be positioned a little toward top. minor though

![pos](https://user-images.githubusercontent.com/2837532/127209389-806dcf45-230a-4ad7-931d-2f66fc793ac9.png)

@kc-leung

2021-08-06 20:32 UTC, merged